release:
  prerelease: auto

changelog:
  use: github-native

env:
  - DOCKER_CLI_EXPERIMENTAL=enabled

gomod:
  proxy: true
  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org

builds:
  - id: darwin-builds
    binary: scs-build
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    main: &build-main ./cmd/scs-build
    mod_timestamp: &build-timestamp '{{ .CommitTimestamp }}'
    env: &build-env
      - CGO_ENABLED=0
    flags: &build-flags '-trimpath'
    ldflags: &build-ldflags |
      -s
      -w
      -X main.version={{ .Version }}
      -X main.date={{ .CommitDate }}
      -X main.builtBy=goreleaser
      -X main.commit={{ .FullCommit }}

  - id: linux-builds
    binary: scs-build
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    main: *build-main
    mod_timestamp: *build-timestamp
    env: *build-env
    flags: *build-flags
    ldflags: *build-ldflags

  - id: windows-builds
    binary: scs-build
    goos:
      - windows
    goarch:
      - amd64
    main: *build-main
    mod_timestamp: *build-timestamp
    env: *build-env
    flags: *build-flags
    ldflags: *build-ldflags

archives:
  - id: darwin-archives
    builds:
      - darwin-builds

  - id: linux-archives
    builds:
      - linux-builds

  - id: windows-archives
    format: zip
    builds:
      - windows-builds

dockers:
  - image_templates:
      - sylabsio/scs-build:{{ .Version }}-amd64
    skip_push: auto
    dockerfile: ./build/docker/scs-build/Dockerfile
    use: buildx
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"

  - image_templates:
      - sylabsio/scs-build:{{ .Version }}-arm64v8
    skip_push: auto
    dockerfile: ./build/docker/scs-build/Dockerfile
    use: buildx
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64/v8"

docker_manifests:
  - name_template: sylabsio/scs-build:latest
    image_templates: &manifest-images
      - sylabsio/scs-build:{{ .Version }}-amd64
      - sylabsio/scs-build:{{ .Version }}-arm64v8
    skip_push: auto

  - name_template: sylabsio/scs-build:{{ .Major }}
    image_templates: *manifest-images
    skip_push: auto

  - name_template: sylabsio/scs-build:{{ .Major }}.{{ .Minor }}
    image_templates: *manifest-images
    skip_push: auto

  - name_template: sylabsio/scs-build:{{ .Major }}.{{ .Minor }}.{{ .Patch }}
    image_templates: *manifest-images
    skip_push: auto

sboms:
  - artifacts: archive
