stages:
  - build

build-code-job:
  stage: build

  image:
    name: "scs-build:latest"

  variables:
    SKIP_VERIFY: "true"

  script:
    - /usr/local/bin/scs-build alpine.def artifact.sif

  artifacts:
    paths:
      - artifact.sif
    expire_in: 1 week
