# Copyright (c) 2022, Sylabs Inc. All rights reserved.
# This software is licensed under a 3-clause BSD license. Please consult the
# LICENSE.md file distributed with the sources of this project regarding your
# rights to use or distribute this software.

stages:
  - build

build-code-job:
  stage: build

  image:
    name: "scs-build:latest"

  variables:
    SKIP_VERIFY: "true"

  script:
    # This example uses cloud.sylabs.io as default builder. Use "--url URL" to specify
    # local Singularity Enterprise environment.
    - /usr/local/bin/scs-build build alpine.def artifact.sif

  artifacts:
    paths:
      - artifact.sif
    expire_in: 1 week
