stages:
  - build

build-code-job:
  stage: build

  image:
    name: "scs-build:latest"

  variables:
    SKIP_VERIFY: "true"

  script:
    # This example uses cloud.sylabs.io as default builder. Use "--url URL" to specify
    # local Singularity Enterprise environment.
    - /usr/local/bin/scs-build build alpine.def artifact.sif

  artifacts:
    paths:
      - artifact.sif
    expire_in: 1 week
